config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :numericality => { :only_integer => true }
  validates :number_of_guests, :numericality => { :only_integer => true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1>Explore All Flats (<%=Flat.count%>) 🏘</h1>

<div class="container">
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="card col-3" style="width: 18rem;">
          <div class="card-body">
            <h5 class="card-title"><%= flat.name %></h5>
            <p class="card-text"><%= flat.address %></p>
            <div class="d-flex">
              <div class="flex"><p><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %></p>
              </div>
              <div class="flex"><p><i class="fas fa-euro-sign"></i><%= flat.price_per_night %></p>
              </div>
          </div>
            <%= link_to 'More info', flat_path(flat) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<h1>Add a new flat 😇</h1>

<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.submit "Add Flat!", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <ul class="nav my-3">
      <li class="nav-item">
        <%= link_to 'Fake Aribnb', flats_path, class: 'nav-link active' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add Flat', new_flat_path, class: 'nav-link btn btn-outline-primary' %>
      </li>
      <li class="nav-item">
        <form role="search" style="width: 15em; margin: 0.3em 2em;">
          <div class="input-group">
              <input type="text" class="form-control" placeholder="Search">
              <div class="input-group-btn">
                  <button type="submit" class="btn btn-default">
                      <span class="glyphicon glyphicon-search"></span>
                  </button>
              </div>
          </div>
        </form>
      </li>
    </ul>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>